# An example workflow using the zScan action that builds an Android application
# in the "build" phase and then runs it against zScan in the "scan" phase.
# The "scan" phase uploads apk to zScan then retrieves and uploads the 
# Zimperium zScan results to GitHub Advanced Security.
# zScan action is run each time a commit is pushed to the "master" branch.

name: "Zimperium zScan Action"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]
    
jobs:
  scan:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Zimperium
      uses: zimperium/zscanmarketplace@v1
      timeout-minutes: 60
      with:
        # REPLACE: Zimperium Client Environment Name
        client_env: ziap
        # REPLACE: Zimperium Client ID
        client_id: xtGeJrz6SF-LvcVJ6Mi5SQ
        # REPLACE: Zimperium Client Secret
        client_secret: ${{ secrets.ZSCAN_CLIENT_SECRET }}
        # REPLACE: The path to an .ipa or .apk
        app_file: DivaApplication.apk

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: Zimperium.sarif

    - name: Move Sarif
      uses: actions/upload-artifact@v3
      with:
        name: sarif
        path: Zimperium.sarif
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
